// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'F:/demo/git_clone_summer/fuckyou/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from 'F:/demo/git_clone_summer/fuckyou/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from 'F:/demo/git_clone_summer/fuckyou/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, CrownOutlined, TableOutlined };
